name: Gatsby Build
on:
  push:
    branches:    
      - master

  repository_dispatch:
    types: build-interim

  schedule:
    - cron: "00 05 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          # gatsby-args: --prefix-paths
        env:
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
